# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kyle/Git/metar-cli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kyle/Git/metar-cli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kyle/Git/metar-cli/CMakeFiles /Users/kyle/Git/metar-cli//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kyle/Git/metar-cli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named metar

# Build rule for target.
metar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metar
.PHONY : metar

# fast build rule for target.
metar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/build
.PHONY : metar/fast

src/ArgParser.o: src/ArgParser.cpp.o
.PHONY : src/ArgParser.o

# target to build an object file
src/ArgParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/ArgParser.cpp.o
.PHONY : src/ArgParser.cpp.o

src/ArgParser.i: src/ArgParser.cpp.i
.PHONY : src/ArgParser.i

# target to preprocess a source file
src/ArgParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/ArgParser.cpp.i
.PHONY : src/ArgParser.cpp.i

src/ArgParser.s: src/ArgParser.cpp.s
.PHONY : src/ArgParser.s

# target to generate assembly for a file
src/ArgParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/ArgParser.cpp.s
.PHONY : src/ArgParser.cpp.s

src/METARParser.o: src/METARParser.cpp.o
.PHONY : src/METARParser.o

# target to build an object file
src/METARParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/METARParser.cpp.o
.PHONY : src/METARParser.cpp.o

src/METARParser.i: src/METARParser.cpp.i
.PHONY : src/METARParser.i

# target to preprocess a source file
src/METARParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/METARParser.cpp.i
.PHONY : src/METARParser.cpp.i

src/METARParser.s: src/METARParser.cpp.s
.PHONY : src/METARParser.s

# target to generate assembly for a file
src/METARParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/METARParser.cpp.s
.PHONY : src/METARParser.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/WebHandler.o: src/WebHandler.cpp.o
.PHONY : src/WebHandler.o

# target to build an object file
src/WebHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/WebHandler.cpp.o
.PHONY : src/WebHandler.cpp.o

src/WebHandler.i: src/WebHandler.cpp.i
.PHONY : src/WebHandler.i

# target to preprocess a source file
src/WebHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/WebHandler.cpp.i
.PHONY : src/WebHandler.cpp.i

src/WebHandler.s: src/WebHandler.cpp.s
.PHONY : src/WebHandler.s

# target to generate assembly for a file
src/WebHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/WebHandler.cpp.s
.PHONY : src/WebHandler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metar.dir/build.make CMakeFiles/metar.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... metar"
	@echo "... src/ArgParser.o"
	@echo "... src/ArgParser.i"
	@echo "... src/ArgParser.s"
	@echo "... src/METARParser.o"
	@echo "... src/METARParser.i"
	@echo "... src/METARParser.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/WebHandler.o"
	@echo "... src/WebHandler.i"
	@echo "... src/WebHandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

